import type { Employee } from "./types";

export const employeeData: Employee[] = [
  {
    id: "E001",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Frontend Developer",
    joinDate: "2022-05-01",
    skills: ["React", "TypeScript", "CSS"],
  },
  {
    id: "E002",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    role: "Backend Developer",
    joinDate: "2021-09-15",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: "E003",
    name: "Carol Davis",
    email: "carol.davis@example.com",
    role: "QA Engineer",
    joinDate: "2023-01-10",
    skills: ["Jest", "Cypress", "Selenium"],
  },
  {
    id: "E004",
    name: "David Lee",
    email: "david.lee@example.com",
    role: "DevOps Engineer",
    joinDate: "2020-08-24",
    skills: ["AWS", "Docker", "Kubernetes"],
  },
  {
    id: "E005",
    name: "Eva Martinez",
    email: "eva.martinez@example.com",
    role: "Project Manager",
    joinDate: "2019-12-11",
    skills: ["Agile", "Scrum", "Communication"],
  },
  {
    id: "E006",
    name: "Frank Wilson",
    email: "frank.wilson@example.com",
    role: "Full Stack Developer",
    joinDate: "2022-03-05",
    skills: ["React", "Node.js", "GraphQL"],
  },
  {
    id: "E007",
    name: "Grace Kim",
    email: "grace.kim@example.com",
    role: "UX Designer",
    joinDate: "2023-06-20",
    skills: ["Figma", "Sketch", "User Research"],
  },
  {
    id: "E008",
    name: "Henry Thompson",
    email: "henry.thompson@example.com",
    role: "Security Analyst",
    joinDate: "2021-10-30",
    skills: ["Penetration Testing", "Firewalls", "Encryption"],
  },
  {
    id: "E009",
    name: "Ivy Chen",
    email: "ivy.chen@example.com",
    role: "Data Scientist",
    joinDate: "2020-07-14",
    skills: ["Python", "Machine Learning", "Data Visualization"],
  },
  {
    id: "E010",
    name: "Jackie Brown",
    email: "jackie.brown@example.com",
    role: "Mobile Developer",
    joinDate: "2022-11-01",
    skills: ["Swift", "Kotlin", "React Native"],

